spring.application.name=ProjetZoo

#Configuration BDD

# spring.datasource.url = jdbc:mysql://localhost:3306/projet_quest
spring.datasource.url = jdbc:mysql://48.220.33.217:3314/projet_zoo
spring.datasource.username = root
spring.datasource.password = 0V+utxijovR2DqWhRYxJcDiHM7YWgTaF

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true


